### ISSUE TITLE
serw13 and probably others: The AX211 wifi card is an E key, not an A key

### ISSUE THREAD

**Issue by ilikenwf** [system76/tech-docs#212] opened 2023-09-27 10:02 UTC
If the slot supports A+E, it should be made more clear please.

Makes it easier to put in a different vendor card.

https://tech-docs.system76.com/models/serw13/repairs.html#replacing-the-wireless-card

**Comment by jacobgkau** [comment] 2023-09-27 20:13
Duplicate of https://github.com/system76/tech-docs/issues/119.

I'll investigate again and try to address this today.

**Closed by jacobgkau** 2023-09-27 20:13 UTC
